"""
Docker setup for the Library Vectorization RAG System

This file provides Docker configurations for easy deployment.
"""

# Docker Compose configuration for development
version: '3.8'

services:
  # Milvus vector database
  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus-standalone
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    depends_on:
      - etcd
      - minio
    networks:
      - rag_network

  # Qdrant vector database (alternative to Milvus)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - rag_network

  # etcd for Milvus
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    volumes:
      - etcd_data:/etcd
    networks:
      - rag_network

  # MinIO for Milvus
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
    command: minio server /minio_data --console-address ":9001"
    volumes:
      - minio_data:/minio_data
    networks:
      - rag_network

  # RAG System Application
  rag-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-system
    ports:
      - "8000:8000"
    environment:
      - VECTOR_STORE_TYPE=milvus
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - EMBEDDING_MODEL=BAAI/bge-small-en-v1.5
      - CHUNKING_STRATEGY=hierarchical
      - LOG_LEVEL=INFO
    volumes:
      - ./documents:/app/documents
      - ./data:/app/data
    depends_on:
      - milvus
    networks:
      - rag_network
    command: python -m src.cli ask --vector-store milvus --collection-name docker_library

volumes:
  milvus_data:
  qdrant_data:
  etcd_data:
  minio_data:

networks:
  rag_network:
    driver: bridge

